name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read

jobs:
  first_j:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo 'First jobdfdfvfd'

  update_release_draft:
    needs: [ first_j ]
    permissions:
      contents: write
      # pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

