name: releaser
on:
  release:
    types: [ published ]

jobs:
  extract-tag-prefix:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract tag prefix and save it
      - name: Extract prefix
        id: extract_prefix
        run: |
            tag="${{ github.ref_name }}" # e.g., release-v1.0.0
            prefix=$(echo "$tag" | sed -E 's/[0-9].*$//') # Extract everything before the first digit
            echo "Tag: $tag"
            echo "Prefix: $prefix"
            echo "PREFIX=$prefix" >> $GITHUB_ENV # Save as an environment variable
      

      # Step 2: Use the tag prefix in another step
      - name: Use the extracted prefix
        run: |
          echo "Using the tag prefix from the environment: ${{ env.PREFIX }}"
